version: "3.8"

services:
  publisher:
    image: basic:deploy
    build:
      context: ..
      dockerfile: docker/Dockerfile.deploy
    container_name: basic-publisher
    network_mode: host
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /workspaces/code/install/setup.bash &&
               ros2 run basic_topic publisher_node"

  subscriber:
    image: basic:deploy
    build:
      context: ..
      dockerfile: docker/Dockerfile.deploy
    container_name: basic-subscriber
    network_mode: host
    depends_on:
      - publisher
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /workspaces/code/install/setup.bash &&
               ros2 run basic_topic subscriber_node"